### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by kwaimind** [kwaimind/makeSuffix#2]
Right now the unit tests are basic and could do with being more detailed.

It would be great to get more tests added to the sub-functions as well as the main makeSuffix function. This will help us find potential bugs and issues I've missed.

**Comment by voodoods** [comment]
@kwaimind Is this issue still open? There seems to be unit tests for each individual function already: https://github.com/kwaimind/makeSuffix/blob/dev/src/index.test.ts#L152-L261

Since these are fairly small functions I don't see much logic that isn't already covered by the existing tests.

**Comment by kwaimind** [comment]
Good catch @voodoods I'll go ahead and close this issue.
