### ISSUE TITLE
TypeScript code review

### ISSUE THREAD

**Issue by kwaimind** [kwaimind/makeSuffix#3]
This is my first real attempt at a TypeScript project. It would be amazing to get some more experienced eyes to take a look at what I've made so far.

**Comment by juanbelieni** [comment]
I don't have that much experience with TypeScript, but I can give a try.

**Comment by kwaimind** [comment]
Hey, yeah go for it and make a PR. Excited to see what you suggest.

**Comment by merelj** [comment]
I've been writing typescript almost exclusively for the last 2,5 years, sure can try to find some stuff to improve 🕵️ 

cool project, btw: never thought of how pluralization worked behind the scenes in english 👍

**Comment by kwaimind** [comment]
@merelj Brilliant. Thanks yeah it was fun to break this thing down actually.
